### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by e11en** [buckyroberts/React-Redux-Boilerplate#10]
I just started following your video tutorial but when I type in `$ webpack` I get the following error:
`ERROR in ./~/css-loader!./~/sass-loader!./dev/scss/style.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Code/React-Redux-Boilerplate/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:237:31)
    at LazyResult.then (/home/user/Code/React-Redux-Boilerplate/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:141:21)
    at processCss (/home/user/Code/React-Redux-Boilerplate/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/home/user/Code/React-Redux-Boilerplate/node_modules/css-loader/lib/loader.js:24:2)
 @ ./dev/scss/style.scss 4:14-122`

What should I do now?

**Comment by e11en** [comment]
So I found a fix for it, you have to run: `$ npm install es6-promise --save` and then add: `require('es6-promise').polyfill();` to your webpack.config.js
